version: 2
archives:
  - format: zip
    name_template: 'terraform-provider-{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - src: LICENSE
        dst: LICENSE.txt
      - src: terraform-registry-manifest.json
        dst: terraform-registry-manifest.json

builds:
  - binary: 'terraform-provider-{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'github.com/hashicorp/terraform-provider-aws/version.ProviderVersion={{ .Version }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - id: gpg
    artifacts: checksum
    args: ["--batch", "--no-tty", "--yes", "-u", "ED9001B16D1E224D", "--output", "${signature}", "--detach-sign", "${artifact}"]
    cmd: gpg
    signature: ${artifact}.sig

release:
  github:
    owner: max-ts0gt
    name: terraform-provider-aws